reformat blocks and transaction responses
dominant-strategies/quais-5.js pull request #15
Opened 2023-11-01 19:14 UTC by DenisIvanov26

2023-11-02 14:08 UTC, wizeguyy commented on packages/abstract-provider/src.ts/index.ts
> +    sha3Uncles: String;
why are some types `String` and others `string`? Does capitalization matter? Are they different types?

2023-11-02 14:08 UTC, wizeguyy commented on packages/providers/src.ts/formatter.ts
> +        const etxs = this.etxs.bind(this)
missing semicolon?

2023-11-02 14:09 UTC, wizeguyy commented on packages/providers/src.ts/formatter.ts
> +            //gasLimit: bigNumber,
just delete it if you don't need it. we can always dig through git history if you want to find it again

2023-11-02 14:09 UTC, wizeguyy commented on packages/providers/src.ts/formatter.ts
> +            //sender: Formatter.allowNull(address),
same as above... delete the cruft

2023-11-02 14:10 UTC, wizeguyy commented on packages/providers/src.ts/formatter.ts
> +            //removed: Formatter.allowNull(this.boolean.bind(this)),
:eyes:

2023-11-02 15:04 UTC, DenisIvanov26 commented on packages/abstract-provider/src.ts/index.ts
> +    sha3Uncles: String;
Capitalization does matter as one is a primitive type while the other is a string object wrapper. Changed all to string.

2023-11-02 15:07 UTC, wizeguyy approved these changes

2023-11-07 16:39 UTC, wizeguyy requested changes
You added two more commits, which are just tweaks of work done in prior commits. Please squash them into the appropriate commits. Otherwise, good to go

2023-11-07 17:24 UTC, DenisIvanov26 commented
> You added two more commits, which are just tweaks of work done in prior commits. Please squash them into the appropriate commits. Otherwise, good to go

Resolved

2023-11-07 17:48 UTC, jdowning100 approved these changes

2023-11-07 18:20 UTC, wizeguyy approved these changes

2023-11-07 18:38 UTC, merged