Ws on block fix
dominant-strategies/quais-5.js pull request #18
Opened 2023-11-03 19:54 UTC by DenisIvanov26

2023-11-03 21:28 UTC, alanorwick requested changes

2023-11-03 21:28 UTC, alanorwick commented on packages/asm/lib.esm/assembler.d.ts
> -export declare type AssembleVisitFunc = (node: Node, bytecode: string) => void;
why were the declares removed?

2023-11-03 21:28 UTC, alanorwick commented on packages/providers/src.ts/websocket-provider.ts
> +                    const blockNumber = BigNumber.from(result.number[2]).toNumber();
2 should be defined as a variable somewhere.

2023-11-07 18:43 UTC, DenisIvanov26 commented
Closed PR as it is a duplicate with PR #10

2023-11-07 18:43 UTC, closed without merging