Adds ETX field to Transaction receipt and adds ETX receipt interface
dominant-strategies/quais-5.js pull request #3
Opened 2023-09-13 19:42 UTC by alanorwick

2023-09-14 17:01 UTC, wizeguyy commented on packages/abstract-provider/lib.esm/index.d.ts
> +    etxs: Array<ETXReceipt>;
I think this can just be the existing `Transaction` type. No need to create a new `ExtTransaction` type or `ETXReceipt` as you've named it.

2023-09-14 17:02 UTC, wizeguyy requested changes
I don't think the new `ETXReceipt` type is correct. See comments.

Also, please squash both commits.

2023-09-14 19:19 UTC, wizeguyy commented on packages/quais/dist/quais.esm.js
How did this small feature (add the `etxs` field to the TransactionReceipt type) result in 175K lines of code? What is this 73K line file?

2023-09-15 16:19 UTC, wizeguyy approved these changes
Much better!

2023-09-15 16:23 UTC, gameofpointers requested changes

2023-09-15 16:23 UTC, gameofpointers commented on packages/quais/dist/quais.umd.js
> +	    Formatter.prototype.etxResponse = function (transaction) {
Do we need this extra formatter for the etxresponse? We use the same data structure for Tx and Etx, so wondering why we need different formatters.

2023-09-15 17:32 UTC, wizeguyy approved these changes

2023-09-15 17:38 UTC, gameofpointers approved these changes

2023-09-15 19:09 UTC, wizeguyy approved these changes

2023-09-15 19:20 UTC, merged